MANAGE_TOKEN="288919-7Lr9j0e25TrXlyMHWDl98V7kHCGZtX3XgrU0bRLY"
ACCOUNT="keboola"
USER="SAPI_WORKSPACE_1218768643"
PASSWORD="ury6mECM6Udjtgp6mPyHYzZfuZA32pi3"
WAREHOUSE="KEBOOLA_PROD_SMALL"
DATABASE="SAPI_10201"
SCHEMA="WORKSPACE_1218768643"